### ISSUE TITLE
Openinghours Resource

### ISSUE THREAD

**Issue by Sch3lp** [Sch3lp/Fiazard#6]
Returns opening hours (seems obvious right?).
Resource `/v1/openinghours` that returns JSON:
```json
[
{
    "day":"1",
    "hours":[{"from":"09:00","until":"12:00"},{"from":"12:30","until":"17:00"}]
},
{
    "day":"2",
    "hours":[{"from":"09:30","until":"12:30"}]
}
]
```
1 = monday. Because we're living in fucking Europe.
This belongs in the *Managing* domain, I think.

**Comment by toonborgers** [comment]
Fixed in pull request #8
